services:
  db:
    container_name: findly-dev-db
    image: postgres:18-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    restart: unless-stopped
    env_file:
      - .env

  web:
    build: .
    container_name: findly-dev-web
    entrypoint: /app/scripts/entrypoint.sh
    volumes:
      - ./cdn/static:/app/cdn/staticfiles
      - ./cdn/media:/app/cdn/media
    ports:
      - "127.0.0.1:${APP_PORT}:8000"
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data:
