# Generated by Django 5.2.7 on 2025-11-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
