# Generated by Django 5.2.7 on 2025-11-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_gender_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=10, verbose_name="Gender"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=15, unique=True, verbose_name="Phone Number"
            ),
        ),
    ]
