# Generated by Django 5.2.7 on 2025-11-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150, null=True, unique=True, verbose_name="Username"
            ),
        ),
    ]
