# Generated by Django 5.2.7 on 2025-11-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="identifier",
            new_name="id",
        ),
    ]
