# Generated by Django 5.2.7 on 2025-11-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_rename_identifier_chat_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="sent_at",
        ),
    ]
