# Generated by Django 5.2.7 on 2025-11-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="broadcast_type",
            field=models.CharField(
                blank=True,
                choices=[("all", "All"), ("target", "Target")],
                max_length=100,
                null=True,
            ),
        ),
    ]
